### ISSUE TITLE
No module named 'utils.bluetooth_utils'

### ISSUE THREAD

**Issue by RwOnke** [ECTO-1A/AppleJuice#10]
Installed all dependencies

**Comment by barsikus007** [comment]
```bash
touch utils/__init__.py
```

**Comment by RwOnke** [comment]
> ```shell
> touch utils/__init__.py
> ```

what do I do with this? I'm kind of a newbie to python

**Comment by RwOnke** [comment]
> ```shell
> touch utils/__init__.py
> ```

Worked like a charm! Thanks so much!!
