### ISSUE TITLE
Raspberry pi 0w 2 - Not working while running 

### ISSUE THREAD

**Issue by 7h30th3r0n3** [ECTO-1A/AppleJuice#11]
I installed everything as recommended on my Raspberry pi 0w 2 (internal BLE), 
but when I launch the program nothing happens on the iPhones around, 
the program seems to be running well, but nothing happens around.

is this related to internal BLE ? 

Edit : does this work on Raspberry pi 0w v1(internal BLE) ? 
Or the external ble dongle is required?

**Comment by DiamondRoPlayz** [comment]
Same here, Patched!?

**Comment by MrWijnen01** [comment]
same sometimes after like 2 minutes it does pop up only if you do your phone 1 cm away from the pi

**Comment by DiamondRoPlayz** [comment]
It randomly worked for a second after leaving it on for an hour and now it won't work again for hours.

**Comment by 7h30th3r0n3** [comment]
Tested on Raspberry pi 0w v1 (internal BLE), same , I should try near the phone ? 
So it's seem to be related to a power issue, the ble transmitter of the rpi is maybe to weak,
so purchase a external dongle is the solution

**Comment by MrYellowHeart** [comment]
You likely need an external adapter to have it work any more than 1-2 feet away from the Pi

**Comment by 7h30th3r0n3** [comment]
> Has someone tried if a external adapter works?

Yes, I tried with the same external ble on the picture, and it's don't seem to work, while I tried only on one phone for couple minutes, I only tried with the app.py, maybe the unique Py file work better for some reason, but not able to get any notification, with and without external ble while the code seem to run well

**Comment by MrWijnen01** [comment]
Strange maybe apple fixed the issue or something else

**Comment by mamhadu** [comment]
Having the same issue but using my laptop. Nothing happens... The phone can find all Bluetooth devices around, but never get a popup.

**Comment by 7h30th3r0n3** [comment]
> Having the same issue but using my laptop. Nothing happens... The phone can find all Bluetooth devices around, but never get a popup.

Same here, it seem that something is not working somewhere but can't identify what, it's running pretty well on flipper zero, so it should work too... I'm gonna deep into the code to see if I can see any issue

**Comment by ECTO-1A** [comment]
Have you changed the hci device to being the external antenna? The raspberry Pi Zero and an external adapter was my original setup for discovering all of these and is still working fine for me, I can get the headphone popups from across the house.

**Comment by 7h30th3r0n3** [comment]
> Have you changed the hci device to being the external antenna? The raspberry Pi Zero and an external adapter was my original setup for discovering all of these and is still working fine for me, I can get the headphone popups from across the house.

After a reinstall of all the project with new update it seem to work well now 💪 
I got notifications across an entire building floor,
It should be related to a permission issue in python but I can't figure out what the mistake,

Any way it work now, let's go for annoying Apple user!! 🤭

**Comment by 7h30th3r0n3** [comment]
All working great, I'm closing the issue

**Comment by wh1ter0z** [comment]
@7h30th3r0n3 hello 

i have rpi pico w how to do upload web wersion ?

**Comment by 7h30th3r0n3** [comment]
> @7h30th3r0n3 hello
> 
> i have rpi pico w how to do upload web wersion ?

Since rpi Pico w is not the same as the rpi 0w, and that the issue is not related, and this issue is closed, maybe you should open a new issue
