### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Kolhax** [ECTO-1A/AppleJuice#12]
![Screenshot_20230908-115800_Termux](https://github.com/ECTO-1A/AppleJuice/assets/92904192/19955ada-37fb-4bf2-a527-ccf0e04266dc)

**Comment by liquidz00** [comment]
What is the output when you run `hci dev`? Does your bluetooth adapter show as `hci0`?

**Comment by chris01b** [comment]
I got this same error when I had no devices in `hcitool dev`.

**Comment by ECTO-1A** [comment]
If it's not showing anything when you run hcitool dev that means it's not recognizing your Bluetooth card and the script won't run.

**Comment by Kolhax** [comment]
I saw that I can't use internal Bluetooth

**Comment by LylCan7i** [comment]
如果在运行 hcitool dev 时未显示任何内容，我应该怎样做呢，我尝试过运行 hciconfig hci0 up 也没有成功。

**Comment by LylCan7i** [comment]
What should I do if nothing is not displayed while running hcitool dev? I have tried running hciconfig hci0 up without success.

**Comment by ExME168** [comment]
Has the Bluetooth service been started on your machine? Plugging in your Bluetooth adapter isn't enough as you'll need to enter
```
service bluetooth start
``` 
to actually make it work. If you're using Kali, the Bluetooth icon should pop up on the top-right.
