### ISSUE TITLE
work only a few times

### ISSUE THREAD

**Issue by neve360** [ECTO-1A/AppleJuice#20]
hi im using an external usb bluetooth adapter on a kali vm (virtualbox macos host [intel]) with latest kernel.
it started a few times the apple tv and the airpods max but after it doesnt work but the bluetooth adapter works in the manager.
with a reboot it works for few times and after still broke.

**Comment by SanderGott** [comment]
Try running btmon before you start the program in another terminal. Does it say Status: Command Disallowed (0x0c)?

**Comment by neve360** [comment]
i think the problem was virtualbox i tried with vmware and now it works
