### ISSUE TITLE
No module named 'bluetooth'

### ISSUE THREAD

**Issue by casparjaeqx** [ECTO-1A/AppleJuice#23]
![Screenshot from 2023-09-11 11-16-12](https://github.com/ECTO-1A/AppleJuice/assets/80122108/8edfe21b-9374-4852-8eca-119284ee10b3)

bluethoot device is showing up in hcitool dev as hci0
running on a pop os laptop with a mediatek wifi / bluethoot card

**Comment by SomeRandom-Dev** [comment]
It looks like you're missing a library, try this command:
`pip3 install pybluez`

**Comment by casparjaeqx** [comment]
> You can't run it as root. Follow the install instructions completely and it should work

if i dont run it as root it complains about not beaing root
![image](https://github.com/ECTO-1A/AppleJuice/assets/80122108/1794990b-9af3-4de0-8abe-1f1bd46c9133)

**Comment by casparjaeqx** [comment]
> It looks like you're missing a library, try this command: `pip3 install pybluez`

if i try your command it says that the requirments are already satified 
![image](https://github.com/ECTO-1A/AppleJuice/assets/80122108/c9ec8b9c-cde3-4c4e-a0ce-28956fdf5449)

**Comment by 7h30th3r0n3** [comment]
> > It looks like you're missing a library, try this command: `pip3 install pybluez`
> 
> if i try your command it says that the requirments are already satified ![image](https://user-images.githubusercontent.com/80122108/267146573-c9ec8b9c-cde3-4c4e-a0ce-28956fdf5449.png)

Can you try this : 
sudo setcap cap_net_raw,cap_net_admin+eip $(eval readlink -f $(which python3))

And try again please

**Comment by 7h30th3r0n3** [comment]
> > > It looks like you're missing a library, try this command: `pip3 install pybluez`
> > 
> > 
> > if i try your command it says that the requirments are already satified ![image](https://user-images.githubusercontent.com/80122108/267146573-c9ec8b9c-cde3-4c4e-a0ce-28956fdf5449.png)
> 
> Can you try this :``` sudo setcap cap_net_raw,cap_net_admin+eip (evalreadlink−f(which python3))```
> 
> And try again

**Comment by casparjaeqx** [comment]
it gives me a syntax error 
![image](https://github.com/ECTO-1A/AppleJuice/assets/80122108/6f57e8b6-8bcc-470c-a8c5-d8729232a2f6)

**Comment by casparjaeqx** [comment]
i think i fixed it took this command:sudo setcap cap_net_raw,cap_net_admin+eip $(eval readlink -f $(which python))  and added the 3 after the python like the command you send me
it now says broadcasting now need to go find a iphone to try it on
thanks for the help
