### ISSUE TITLE
Modulenotfounderror: utils.bluetooth_utils

### ISSUE THREAD

**Issue by Nictadyneni** [ECTO-1A/AppleJuice#31]
Hello, 
I'm using kalinethunter on oneplus7t with external bluetooth adapter. When i start:
Python3 app.py 
I get error message about module missing
ModuleNotFoundError: no module name 'utils.bluetooth_utils' ; utils is not package

Do you have an idea where I'm making mistake? Thanks

**Comment by shadow22852** [comment]
I have the same problem. Try to rename folder "utils" to "utils1" for ex, then in file app.py change code to "from utils1.bluetooth_utils import (toggle_device, start_le_advertising, stop_le_advertising)"
They're a folder "utils" in standart python library which has no file bluetooth_utils.

**Comment by Nictadyneni** [comment]
thanks, that helped!
